#!/bin/sh
set -e
# Automatically added by dh_installinit/13.2~bpo10+1
if [ -x "/etc/init.d/dump1090-fa" ] && [ "$1" = remove ]; then
	invoke-rc.d dump1090-fa stop || exit 1
fi
# End automatically added section
# Automatically added by dh_systemd_start/13.2~bpo10+1
if [ -d /run/systemd/system ]; then
	deb-systemd-invoke stop 'dump1090-fa.service' >/dev/null || true
fi
# End automatically added section
